disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping

included:
  - Sources

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length: 2
  excluded:
    - id
    - c
